#!/usr/bin/env bash
# Validate a staged runtime tree and produce a release tarball + sha256 sidecar.
#
# Usage:
#   package-runtime.sh <staging-dir> <php-version> <target> [output-dir]
#
# staging-dir must contain bin/php and bin/composer (executables).
# Dynamic runtime staging dirs may also include ext/, etc/, lib/, include/, and metadata/.
# Output:
#   php-{version}-{target}.tar.gz
#   php-{version}-{target}.tar.gz.sha256
set -euo pipefail

usage() {
  echo "Usage: $0 <staging-dir> <php-version> <target> [output-dir]" >&2
  exit 1
}

[[ $# -ge 3 && $# -le 4 ]] || usage

STAGING="$(cd "$1" && pwd)"
PHP_VERSION="$2"
TARGET="$3"
OUT_DIR="${4:-$(pwd)}"

if [[ ! -d "${STAGING}/bin" ]]; then
  echo "error: staging dir missing bin/: ${STAGING}" >&2
  exit 1
fi

for bin in php composer; do
  if [[ ! -x "${STAGING}/bin/${bin}" ]]; then
    echo "error: missing executable ${STAGING}/bin/${bin}" >&2
    exit 1
  fi
done

# Smoke test PHP before packaging. Static builds must expose every catalog
# extension through php -m. (Dynamic verification paths are legacy.)
"${STAGING}/bin/php" -v >/dev/null
if [[ -d "${STAGING}/ext" ]]; then
  PHPRC="${STAGING}/etc" PHP_INI_SCAN_DIR="${STAGING}/etc/conf.d" "${STAGING}/bin/composer" -V >/dev/null
  "$(dirname "${BASH_SOURCE[0]}")/verify-dynamic-runtime.sh" "${STAGING}"
else
  "${STAGING}/bin/composer" -V >/dev/null
  "$(dirname "${BASH_SOURCE[0]}")/verify-extensions.sh" "${STAGING}/bin/php"
fi

ARCHIVE_NAME="php-${PHP_VERSION}-${TARGET}.tar.gz"
ROOT_NAME="php-${PHP_VERSION}-${TARGET}"
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

PACK_ROOT="${WORK}/${ROOT_NAME}"
mkdir -p "${PACK_ROOT}/bin"
cp -a "${STAGING}/bin/php" "${PACK_ROOT}/bin/"
cp -a "${STAGING}/bin/composer" "${PACK_ROOT}/bin/"
if [[ -f "${STAGING}/bin/composer.phar" ]]; then
  cp -a "${STAGING}/bin/composer.phar" "${PACK_ROOT}/bin/"
fi

# Copy optional runtime deps and dynamic bundle directories without following external symlinks.
for dir in ext etc lib include metadata licenses; do
  if [[ -d "${STAGING}/${dir}" ]]; then
    cp -a "${STAGING}/${dir}" "${PACK_ROOT}/"
  fi
done
if [[ -f "${STAGING}/THIRD_PARTY_NOTICES" ]]; then
  cp -a "${STAGING}/THIRD_PARTY_NOTICES" "${PACK_ROOT}/"
fi

if [[ -d "${PACK_ROOT}/ext" ]]; then
  mkdir -p "${PACK_ROOT}/etc/conf.d"
  cat > "${PACK_ROOT}/etc/php.ini" <<'EOF'
; Base php.ini for a phpvm dynamic runtime.
; phpvm refreshes extension_dir and default extension snippets after extraction.
display_errors = On
error_reporting = E_ALL
EOF
  cat > "${PACK_ROOT}/etc/conf.d/00-default.ini" <<'EOF'
; Generated by phpvm after extraction.
; Required default extensions are written with install-specific absolute paths.
EOF
fi

mkdir -p "${OUT_DIR}"
ARCHIVE_PATH="${OUT_DIR}/${ARCHIVE_NAME}"

tar -C "${WORK}" -czf "${ARCHIVE_PATH}" "${ROOT_NAME}"

if command -v sha256sum >/dev/null 2>&1; then
  sha256sum "${ARCHIVE_PATH}" | awk '{print $1}' > "${ARCHIVE_PATH}.sha256"
else
  shasum -a 256 "${ARCHIVE_PATH}" | awk '{print $1}' > "${ARCHIVE_PATH}.sha256"
fi

echo "packaged ${ARCHIVE_PATH}"
echo "checksum $(cat "${ARCHIVE_PATH}.sha256")"
