#!/usr/bin/env bash
# Generate craft.yml from builds/common/extensions.json (single source of truth).
#
# Usage:
#   render-craft.sh builds/8.3.31
#   render-craft.sh --all
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXT_JSON="${ROOT}/builds/common/extensions.json"

render_one() {
  local craft_dir="$1"
  local version
  version="$(basename "${craft_dir}")"

  if [[ ! "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "error: expected builds/MAJOR.MINOR.PATCH, got ${craft_dir}" >&2
    exit 1
  fi

  if [[ ! -f "${EXT_JSON}" ]]; then
    echo "error: ${EXT_JSON} not found" >&2
    exit 1
  fi

  if ! command -v jq >/dev/null 2>&1; then
    echo "error: jq is required" >&2
    exit 1
  fi

  local minor extensions
  minor="${version%.*}"
  extensions="$(jq -r '.spc | join(",")' "${EXT_JSON}")"

  mkdir -p "${craft_dir}"
  cat > "${craft_dir}/craft.yml" <<EOF
# GENERATED by scripts/render-craft.sh — edit builds/common/extensions.json instead.
php-version: "${minor}"
extensions: "${extensions}"
sapi:
  - cli
download-options:
  parallel: 10
EOF
  echo "rendered ${craft_dir}/craft.yml (php ${minor}, $(jq '.spc | length' "${EXT_JSON}") spc extensions)"
}

if [[ "${1:-}" == "--all" ]]; then
  shopt -s nullglob
  for craft_dir in "${ROOT}"/builds/[0-9]*.[0-9]*.[0-9]*; do
    render_one "${craft_dir}"
  done
  exit 0
fi

[[ $# -eq 1 ]] || {
  echo "Usage: $0 builds/<php-version> | --all" >&2
  exit 1
}

CRAFT_DIR="$1"
[[ "${CRAFT_DIR}" != /* ]] && CRAFT_DIR="${ROOT}/${CRAFT_DIR}"
render_one "${CRAFT_DIR}"
