#!/usr/bin/env bash
# Sync builds/<php-version>/ recipe directories from a catalog plan.
set -euo pipefail

usage() {
  cat >&2 <<'EOF'
Usage:
  sync-runtime-recipes.sh --plan plan.json
EOF
  exit "${1:-1}"
}

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PLAN=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --plan)
      [[ $# -ge 2 ]] || usage
      PLAN="$2"
      shift 2
      ;;
    -h|--help)
      usage 0
      ;;
    *)
      echo "error: unknown argument: $1" >&2
      usage
      ;;
  esac
done

[[ -n "${PLAN}" ]] || usage
[[ -f "${PLAN}" ]] || {
  echo "error: plan not found: ${PLAN}" >&2
  exit 1
}

if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq is required" >&2
  exit 1
fi

mapfile -t DESIRED < <(jq -r '.desired_versions[]' "${PLAN}")
[[ "${#DESIRED[@]}" -gt 0 ]] || {
  echo "error: plan has no desired_versions" >&2
  exit 1
}

declare -A KEEP=()
for version in "${DESIRED[@]}"; do
  if [[ ! "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "error: invalid PHP version in plan: ${version}" >&2
    exit 1
  fi

  KEEP["${version}"]=1
  dir="${ROOT}/builds/${version}"
  mkdir -p "${dir}"
  "${ROOT}/scripts/render-craft.sh" "builds/${version}"

  cat > "${dir}/notes.md" <<EOF
# PHP ${version}

Generated by scripts/sync-runtime-recipes.sh from the catalog update plan.

\`craft.yml\` pins the ${version%.*} minor line. Verify \`buildroot/bin/php -v\`
reports ${version} before packaging.
EOF
done

shopt -s nullglob
for dir in "${ROOT}"/builds/[0-9]*.[0-9]*.[0-9]*; do
  version="$(basename "${dir}")"
  if [[ -z "${KEEP[${version}]:-}" ]]; then
    rm -rf "${dir}"
    echo "removed builds/${version}"
  fi
done

echo "runtime recipes synced: ${#DESIRED[@]} version(s)"
